import { Node } from "../components/Visualization";

export default {
  nodes: [
    {
      id: "Node 1",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 2",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 3",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 4",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 5",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 6",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 0",
      height: 2,
      size: 32,
      color: "rgb(244, 117, 96)",
    },
    {
      id: "Node 1.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.7",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.8",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.7",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 5.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 5.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 5.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
  ] as Node[],
  links: [
    {
      source: "Node 0",
      target: "Node 1",
      distance: 80,
    },
    {
      source: "Node 1",
      target: "Node 1.0",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.1",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.2",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.3",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.4",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.5",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.6",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.7",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.8",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 2",
      distance: 80,
    },
    {
      source: "Node 2",
      target: "Node 2.0",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.1",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.2",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.3",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.4",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.5",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.6",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 3",
      distance: 80,
    },
    {
      source: "Node 3",
      target: "Node 3.0",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.1",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.2",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.3",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.4",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.5",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.6",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 4",
      distance: 80,
    },
    {
      source: "Node 4",
      target: "Node 4.0",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.1",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.2",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.3",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.4",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.5",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.6",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.7",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 5",
      distance: 80,
    },
    {
      source: "Node 5",
      target: "Node 1",
      distance: 80,
    },
    {
      source: "Node 5",
      target: "Node 3",
      distance: 80,
    },
    {
      source: "Node 5",
      target: "Node 5.0",
      distance: 50,
    },
    {
      source: "Node 5",
      target: "Node 5.1",
      distance: 50,
    },
    {
      source: "Node 5",
      target: "Node 5.2",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 6",
      distance: 80,
    },
    {
      source: "Node 6",
      target: "Node 1",
      distance: 80,
    },
    {
      source: "Node 6",
      target: "Node 6.0",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.1",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.2",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.3",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.4",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.5",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.6",
      distance: 50,
    },
  ],
};
